### ISSUE TITLE
unexpected behavior in firefox, uploading disappears while clicking new object in bucket. 

### ISSUE THREAD

**Issue by koolhead17** [minio/miniobrowser#63] opened 2016-02-06 14:16 UTC
On firefox[44] i was uploading 800 MB file, all went well unless i clicked on another object an image which opened in browser resulting in stopping the upload.

**Comment by harshavardhana** [comment] 2016-02-08 05:23
Duplicate of #72

**Closed by harshavardhana** 2016-02-08 05:23 UTC
Labels: duplicate
