### ISSUE TITLE
unexpected UI behavior after logging out.

### ISSUE THREAD

**Issue by koolhead17** [minio/miniobrowser#62] opened 2016-02-06 11:59 UTC
Hi,
I saved my access/secret key in Firefox web browser. Once i logged out, I see the default text overlapping with the credentials. Screenshot attached. Firefox version 44[Mac]
![git](https://cloud.githubusercontent.com/assets/41746/12866527/b79a984c-ccf6-11e5-95fa-a4cfa56e336a.png)

**Comment by harshavardhana** [comment] 2016-02-08 05:23
Duplicate of #72

**Closed by harshavardhana** 2016-02-08 05:23 UTC
Labels: duplicate
