### ISSUE TITLE
How to delete files and buckets?

### ISSUE THREAD

**Issue by nodesocket** [minio/miniobrowser#154] opened 2016-05-05 07:39 UTC
I might be missing it, but how do you delete files and buckets in the web interface?

**Comment by harshavardhana** [comment] 2016-05-05 07:42
> I might be missing it, but how do you delete files and buckets in the web interface?

We deliberately did not add as a safety mechanism so that users don't accidentally delete a whole bunch of files - usually a common possibility. 

If you still wish to delete files and buckets you can use - https://github.com/minio/mc , has a handy command line tool.

**Comment by nodesocket** [comment] 2016-05-05 07:46
Ok makes sense, but I feel deleting could be done just on files in the browser list. When you click delete, pop open a modal with a confirmation. I would think that would be enough of a verification.

I'd really like to see deleting of files implemented in the web interface.

**Comment by harshavardhana** [comment] 2016-05-05 07:57
> Ok makes sense, but I feel deleting could be done just on files in the browser list. When you click delete, pop open a modal with a confirmation. I would think that would be enough of a verification.
> 
> I'd really like to see deleting of files implemented in the web interface.

We will discuss internally on how safely this can be implemented.

**Comment by harshavardhana** [comment] 2016-10-01 08:11
Fixed by

https://github.com/minio/miniobrowser/pull/194

and 

https://github.com/minio/miniobrowser/pull/195

**Closed by harshavardhana** 2016-10-01 08:11 UTC
Labels: enhancement, future

**Comment by nodesocket** [comment] 2016-10-06 06:13
Is this already pushed lived? I'm not seeing the option to delete files and buckets?

**Comment by GarimaKapoor** [comment] 2016-10-06 06:18
@nodesocket, The issue is fixed and will come with the next release.

**Comment by jGielen** [comment] 2017-01-12 11:15
@harshavardhana, is the part of deleting buckets already handled in the web interface?

**Comment by nodesocket** [comment] 2017-01-13 10:58
When is the next release? I just tried today **1/13/17** and still no way to delete buckets and files.
